### ISSUE TITLE
this.server.currentLayer.layer is null on Jensens Range. 

### ISSUE THREAD

**Issue by ect0s** [Thomas-Smyth/SquadJS#213]
https://github.com/Thomas-Smyth/SquadJS/blob/f825b4a65b486fd1cd738480e732afe74eb13aec/squad-server/layers/layers.js#L43

Jensens Range has 3 entries in 

https://raw.githubusercontent.com/Squad-Wiki-Editorial/squad-wiki-pipeline-map-data/master/completed_output/_Current%20Version/finished.json

With Identical Names, as returned by RCON. 

In the case of Jensens Range, we end up with matches having 3 entries, failing the equality check against `.length === 1`

The length check match means we pass null when the map is ambigious, this breaks server status and the currentlayer/layerhistory in the server object.

```
           "Name": "Jensen's Training Range",
            "rawName": "CAF_JensensRange_CAF-RUS",
            "levelName": "CAF_Jensens_Range_v4",
            
            "Name": "Jensen's Training Range",
            "rawName": "JensensRange_GB-MIL",
            "levelName": "Jensens_Range_v1",
            
            "Name": "Jensen's Training Range",
            "rawName": "JensensRange_US-RUS",
            "levelName": "Jensens_Range_v2",
            
            "Name": "Jensen's Training Range",
            "rawName": "JensensRange_MEA-INS",
            "levelName": "Jensens_Range_v3", 
```
            
            

            
Without more information, I'm not sure we can disambiguate the current map, perhaps a hook into the log file/new game event?

It appears we do this with layer classname on new game, however the intervaled update at 

https://github.com/Thomas-Smyth/SquadJS/blob/f825b4a65b486fd1cd738480e732afe74eb13aec/squad-server/index.js#L400

Is where we fail to update the layer information correctly, overwriting the current map information with "null"

**Comment by werewolfboy13** [comment]
This is excluded in the new layers.json as per the Wiki guidance. So it will not show in the bot anymore.

**Comment by ect0s** [comment]
> This is excluded in the new layers.json as per the Wiki guidance. So it will not show in the bot anymore.

What exactly do you mean, all Jensens layers are removed from the output JSON?

**Comment by reck1610** [comment]
#### Jensens Range not in Squad Wiki
This is the link currently used in SquadJS (contains Jensens):
https://raw.githubusercontent.com/Squad-Wiki/squad-wiki-pipeline-map-data/master/completed_output/_Current%20Version/finished.json

This link does not contain Jensens (posted above): 
https://raw.githubusercontent.com/Squad-Wiki-Editorial/squad-wiki-pipeline-map-data/master/completed_output/_Current%20Version/finished.json

@werewolfboy13 You are involved in the Squad Wiki project, correct? Is this behavior intentional or does the first file contain Jensens by accident / is obsolete?


#### Ambiguous layer names
We could use the team information we get from `A2S_INFO` as a fallback.

The team info looks like this:
```
{"TeamOne_s":"Kohat_RAAS_v08_AUS","TeamTwo_s":"Kohat_RAAS_v08_RUS"}
{"TeamOne_s":"GooseBay_RAAS_v3_USMC","TeamTwo_s":"GooseBay_RAAS_v3_RUS"}
```
We could just take the overlap of `TeamOne_s` and `TeamTwo_s` and try to look up the layer with that.

**Comment by werewolfboy13** [comment]
> #### Jensens Range not in Squad Wiki
> This is the link currently used in SquadJS (contains Jensens): https://raw.githubusercontent.com/Squad-Wiki/squad-wiki-pipeline-map-data/master/completed_output/_Current%20Version/finished.json
> 
> This link does not contain Jensens (posted above): https://raw.githubusercontent.com/Squad-Wiki-Editorial/squad-wiki-pipeline-map-data/master/completed_output/_Current%20Version/finished.json
> 
> @werewolfboy13 You are involved in the Squad Wiki project, correct? Is this behavior intentional or does the first file contain Jensens by accident / is obsolete?
> 
> #### Ambiguous layer names
> We could use the team information we get from `A2S_INFO` as a fallback.
> 
> The team info looks like this:
> 
> ```
> {"TeamOne_s":"Kohat_RAAS_v08_AUS","TeamTwo_s":"Kohat_RAAS_v08_RUS"}
> {"TeamOne_s":"GooseBay_RAAS_v3_USMC","TeamTwo_s":"GooseBay_RAAS_v3_RUS"}
> ```
> 
> We could just take the overlap of `TeamOne_s` and `TeamTwo_s` and try to look up the layer with that.

Do not use the old link, we have moved over to a different org. I don't provide support on the old resource. I did a PR fixing that. 

Actually looking at this I am going to close this out as wont fix. As this is an extremely outdated ticket. I recommend that you update your squad instance to the current version

**Comment by werewolfboy13** [comment]
If you are still having any other issues make a ticket regarding those. The issue in this ticket is stale.
