### ISSUE TITLE
High Latency in Log Parser

### ISSUE THREAD

**Issue by LucyferHW** [Thomas-Smyth/SquadJS#214]
### Info from console
`[LogParser][1] Lines parsed per minute: 38 lines per minute | Matching lines per minute: 6 matching lines per minute | Average matching latency: 3058.8333333333335ms`

Hello, I am new to SquadJS I installed it a month ago.
Most of the things are working well, but some triggers/events like `!admin` and teamkill are working fine. But things like createdSquad or RoundWinner are coming from time to time, or not coming at all.

I found that line above in the command line could be that the reason?
If yes, could you say please what could be the problem?

Best regards MHW

### Settings

Squad Server and SquadJS are running on separate machines.

```
"server": {
    "id": 1,
    "host": "host",
    "queryPort": queryPort,
    "rconPort": rconPort,
    "rconPassword": "rconPassword",
    "logReaderMode": "ftp",
    "logDir": "/SquadGame/Saved/Logs",
    "ftp": {
      "port": port,
      "user": "user",
      "password": "password",
      "useListForSize": false
    },
    "adminLists": [
      {
        "type": "local",
        "source": "/home/gsgsquadjs/Admins.cfg"
      }
    ]
  },
```

`adminLists ` is manualy copied to the directory.

```
"logger": {
    "verboseness": {
      "SquadServer": 9,
      "LogParser": 2,
      "RCON": 1
    },
  }
```
`SquadServer` is 9 because I wanted all information

**Comment by Thomas-Smyth** [comment]
That's 3 seconds of latency on average.

What log reader mode are you using? FTP? If so, what are your settings for that?

**Comment by LucyferHW** [comment]
Thanks for looking at my issue.

I have updated the Ticket.

**Comment by immervoll** [comment]
@MHWcreations make sure you're FTP connection is stable and does not trigger some sort of flood protection on the server

**Comment by LucyferHW** [comment]
The FTP connection is between a Root-Server(online 1GBit) and a Squad-Instance. It is stable.

The thing is, triggers/events like `!admin` and teamkill are working fine. But things like createdSquad or RoundWinner are coming from time to time, or not coming at all.

I have now disabled the plugins that I don't need, but in future it would be nice to use all features. 

Is there anything that I could make?

**Comment by Thomas-Smyth** [comment]
Can you be more specific, what plugins are laggy and why are you considering them to be laggy?

**Comment by LucyferHW** [comment]
What I mean:
The thing is, triggers/events like !admin and teamkill are working fine. But things like createdSquad or RoundWinner are coming from time to time, or not coming at all.

The word *laggy* is not very accurate, sorry for that.
