### ISSUE TITLE
Implement an option to use SFTP opposed to FTP

### ISSUE THREAD

**Issue by roengle** [Thomas-Smyth/SquadJS#223]
### What is the issue, e.g. map voting, you would like to solve?
SquadJS only uses FTP and cannot use SFTP.

### How would you like us to solve this issue?
Implement the use of SFTP, possibly as another option as opposed to using normal FTP.

### Additional Info
N/A

**Comment by HansaFL** [comment]
A lot of hosted options only allow for SFTP protocols to access log/admin files. Probably becoming a high severity issue nowadays.

**Comment by Destructor** [comment]
Need this

**Comment by DA-AshleyJ** [comment]
This is 100% needed

**Comment by Thomas-Smyth** [comment]
Implemented in #370.
