### ISSUE TITLE
SquadJS crashes parsing new seed maps from layer api

### ISSUE THREAD

**Issue by cynobill** [Thomas-Smyth/SquadJS#227]
v3.1.0 (Windows Server 2019), node: 16.3.1)  The new seed maps returned from by layer api endpoint are missing vehicle entries.   This causes the layer module to throw an exception on when counting tanks/heli (layer.js line 33).  This crashes SquadJS preventing it from loading

**Comment by ect0s** [comment]
A temporary fix has been applied to the JSON SquadJS pulls. 

A more stable fix is awaiting code review in a PR.
