### ISSUE TITLE
Logger timestamps

### ISSUE THREAD

**Issue by Steezycoding** [Thomas-Smyth/SquadJS#231]
### What is the issue, e.g. map voting, you would like to solve?
Logs have no timestamp yet. 
It would be very useful to debug some stuff especially when you need to match Squad server and SquadJS outputs.

### How would you like us to solve this issue?
It would be great to implement an option in config.json OR a parameter to pass to Logger.verbose() method to activate/deactivate timestamps.

e.g. Logger.verbose(<module>,<verboseness>,<message>, true|false);

**Comment by Thomas-Smyth** [comment]
Should probably just add it to the logger and not worry about the config or parameter - it's not something people are going to strongly disagree with using and it's not a good idea to manage it per logline.
