### ISSUE TITLE
Possible Memory Leak 

### ISSUE THREAD

**Issue by mattjons0n** [Thomas-Smyth/SquadJS#249]
### Description of Issue
Bot fails at doing any task over Rcon due to potential Memory leak

Error:  (node:3891673) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added to [Socket]. Use emitter.setMaxListeners() to increase limitError:  (Use `node --trace-warnings ...` to show where the warning was created)[LogParser][1] Lines parsed per minute: 807 lines per minute | Matching lines per minute: 186 matching lines per minute | Average matching latency: 1255.1290322580646ms

Output after above error:
[RCON][1] Unknown packet type 16777231 in: { size: 256, id: -1946157056, type: 16777231, body: '\x00\x00\x00\x00\x00\x00\x00----- Active Players -----\nID: 71 | SteamID: 76561199086558645 | Name: (   ÍœÍžÊ– ) | Team ID: 1 | Squad ID: 4 | Is Leader: False | Role: USA_Rifleman_03\nID: 75 | SteamID: 76561199259877501 | Name: 2945183**9 | Team ID: 1 | Squad ID: 4 | I' }

After above Unknown packet type output, no more Rcon log type 1 with player information is shown and below is looped.

[RCON][2] Writing packet with type "2" and body "ListPlayers".
[SquadServer][1] Updated A2S information.
[SquadServer][1] Updating player list...
[RCON][2] Writing packet with type "2" and body "ListPlayers".
[SquadServer][1] Updating player list...
[RCON][2] Writing packet with type "2" and body "ListPlayers".
[SquadServer][1] Updating player list...
[RCON][2] Writing packet with type "2" and body "ListPlayers".
[SquadServer][1] Updating player list...
[RCON][2] Writing packet with type "2" and body "ListPlayers".
[SquadServer][1] Updating player list...
[RCON][2] Writing packet with type "2" and body "ListPlayers".
[SquadServer][1] Updating player list...
[RCON][2] Writing packet with type "2" and body "ListPlayers".
[SquadServer][1] Updating player list...

### Squad Information
 * SquadJS Version: 3.4.0
 * Squad Version: 3.1.0

If potentially relevant, please provide regarding the state of the Squad server at the time of error, e.g. the current layer.

### System Information
 * Operating System: Ubuntu 20.04
 * NodeJS Version: 16.15.1
 * Yarn Version: 1.22.10

**Comment by lbzepoqo** [comment]
I happen to encounter this a lot. We are testing a map vote plugin and I really thought the plugin was causing the issue. Then, when I tried using other commands from other plugins like AdminRequests plugin, it doesn't notify the admin or log the request on discord anymore.

Saw this error in squadjslog.log

```
8.0 1:48:42 > [RCON][1] Unknown packet type 16777231 in: { size: 256, id: -1040187392, type: 16777231, body: '\x00\x00\x00\x00\x00\x00\x00----- Active Players -----\nID: 66 | SteamID: 76561198089568541 | Name: ==  M a d d o g  == | Team ID: 2 | Squad ID: 1 | Is Leader: False | Role: INS_Rifleman_05\nID: 20 | SteamID: 76561199140789896 | Name: AR15teen | Team ID: 2 | Squad ID: ' } 
```

Attached is a snippet of the SquadGame.log when it happened with verbose logging enabled.
[SquadGame.log](https://github.com/Team-Silver-Sphere/SquadJS/files/9592124/SquadGame.log)

Please tell me to attach more logs if needed, since I had collected a lot of this error today on our logs.

**Comment by werewolfboy13** [comment]
Resolved on #258

**Comment by ect0s** [comment]
This is not resolved by that PR.

This has nothing to do with that PR

**Comment by werewolfboy13** [comment]
Duplicate of #200
