### ISSUE TITLE
Readme template: SquadLayerFilter Dead Code?

### ISSUE THREAD

**Issue by ect0s** [Thomas-Smyth/SquadJS#254]
### Description of Issue

The readme template has references to squad layer filter, which I'm unfamiliar with; I tried tracing it back inside of the git history and this looks like dead code/documentation to me?

https://github.com/Team-Silver-Sphere/SquadJS/blob/master/squad-server/templates/readme-template.md#squad-layer-filter

I'm unfamiliar with what this was trying to do ( Build a filtered Layer list for plugins to use?)

**Comment by Thomas-Smyth** [comment]
I agree, it looks to be dead code, so it can probably be safely removed.
