### ISSUE TITLE
[Socket.io] Depends on engine.io with known issues

### ISSUE THREAD

**Issue by DrKittens** [Thomas-Smyth/SquadJS#263]
### Description of Issue
SquadJS depends on an old version of socket.io which depends on an instance of engine.io with known problems
https://github.com/advisories/GHSA-r7qp-cfhv-p84w

remediation by upgrading the socket.io dependancy to a version that doesnt depend on engine.io with this fault resolves the problem. I've been running SquadJS with socket.io@4.5.4 and engine.io@6.2.1 for a few days without encountering any new faults.

### Errors or Screenshots of Issue
https://github.com/advisories/GHSA-r7qp-cfhv-p84w

### Squad Information
 * SquadJS Version: 3.6.1 release
 * Squad Version: N/A

If potentially relevant, please provide regarding the state of the Squad server at the time of error, e.g. the current layer.

### System Information
 * Operating System: RHEL9
 * NodeJS Version: v18.12.1
 * Yarn Version: v8.19.2

**Comment by werewolfboy13** [comment]
So this and #262 will need more vetting to make sure the changes are not breaking.

**Comment by DrKittens** [comment]
Is there any additional information i can provide to help with this?

**Comment by werewolfboy13** [comment]
@DrKittens I am needing to make sure that both version bumps are not code breaking.
