### ISSUE TITLE
Improve custom plugin support

### ISSUE THREAD

**Issue by reck1610** [Thomas-Smyth/SquadJS#280]
### What is the issue, e.g. map voting, you would like to solve?
In my opinion, custom plugins have 2 problems at the moment.

#### 1. Custom base classes for plugins will always be loaded as a plugin.
This might not cause a problem, but it causes custom plugins to be handled differently from default plugins.
Currently, the default base classes are blacklisted in the plugin loader. 

#### 2. Custom plugins have to be placed in a hard-coded location in the repo
This causes git changes and makes updating SquadJS harder.
This also reduces maintainability for both custom and default plugins, if custom plugins are used. 

### How would you like us to solve this issue?
**Problem1:** I would like to introduce the file extension `.squad.js` for plugins. This removes the need for blacklisting other files in the plugin directory.

**Problem 2:** I would like to make it configurable from where SquadJS is loading the plugins. Furthermore, I would like to allow multiple paths to be configured in order to increase maintainability for both custom and default plugins, if custom plugins are used. 
I would like to introduce `pluginPaths` into the `server` configuration like this:
``` json
{
  "server": {
    "id": 1,
    "host": "xxx.xxx.xxx.xxx",
    "queryPort": 27165,
    "rconPort": 21114,
    "rconPassword": "password",
    "logReaderMode": "tail",
    "logDir": "C:/path/to/squad/log/folder",
    "ftp": {
      "port": 21,
      "user": "FTP Username",
      "password": "FTP Password",
      "useListForSize": false
    },
    "pluginPaths": [
      "squad-server/plugins/",
      "/opt/custom-squadjs-plugins/"
    ]
  }
```

Both relative and absolute paths should be allowed. Plugins will be loaded in order (starting with index 0), if a plugin already exists it will be replaced. This should be logged accordingly.

### Additional Info
I am already working on this.
This relates to #275.

**Comment by werewolfboy13** [comment]
Please see attached PR. Closing as we are not able to proceed with this major change but will keep in mind.
