### ISSUE TITLE
Suggestions for more future add-ons for SQUAD JS

### ISSUE THREAD

**Issue by TLlove798** [Thomas-Smyth/SquadJS#301]
Can SQUAD JS release these plugins later?
1. He can automatically detect cheaters based on injury records and output this information to the bound Discord for easy handling by the administrator
2. For example, some servers have regulations on the team name/number of teams, can JS provide something similar to a custom function, allowing the administrator to set some things that will be processed automatically? For example, some servers do not allow the team members of the vehicle to use Heavy Anti-Tank. When the plugin detects this behavior, it automatically kicks the member.
3. In many cases, the KDA of both sides is very different after each game, which will make people very uncomfortable to play. Can the plug-in randomly change the camp according to the KDA of each person in this game, so as to achieve the strength of both sides is almost balanced?

**Comment by TLlove798** [comment]
Here is another point to add, when can OWI output the FOB log, as well as more detailed information such as whether the person in the damage record is inside the vehicle, and why is there often Null in the damage record

**Comment by steelskillet** [comment]
For 2 and 3, these are usually done as plugins that each community develops and/or modifies. You should check out the squad rcon discord for plugins people have made.
For 1 this can be done by modifying squadjs's log parser slightly and making the events and associating discord plugin
And for your last comment, you should look into modifying your server's .ini config file. You can change what logs the server outputs there

For 3 one of the major problems i find with this is that usually all the 'good' players are playing as a group of friends and the moment you randomize them they will try to get back together on the same team again.

**Comment by werewolfboy13** [comment]
> Here is another point to add, when can OWI output the FOB log, as well as more detailed information such as whether the person in the damage record is inside the vehicle, and why is there often Null in the damage record

This really isn't an issue for this GitHub.
