### ISSUE TITLE
Incorrect path given in config

### ISSUE THREAD

**Issue by ambroiseRabier** [Thomas-Smyth/SquadJS#302]
### What is the issue, e.g. map voting, you would like to solve?
Avoid the error message:
```
Error: ENOENT: no such file or directory, access '\SquadGame\Saved\Logs/SquadGame.log'
```
due to misconfiguration, that itself is due to `logReaderMode` `tail` option not being well named.

### How would you like us to solve this issue?
You can keep `tail` value for legacy, but in the documentation, change `tail` to `local`, and support both `tail` and `local` in code.

### Additional Info

If I am not wrong, in both case (ftp or local), the program tails the log file. So when I read the documentation, I left the option to default `tail`. I got greeted by the error above, and I thought for 30min that I configured a wrong path. Turns out, I had to change `tail` to `ftp`.

**Comment by werewolfboy13** [comment]
@ambroiseRabier This should already be in the documentation. I am going to close this as it is already written.

**Comment by werewolfboy13** [comment]
This also appears to be user error as you may have messed up the path you are pointing to
