### ISSUE TITLE
JS file check breaks application

### ISSUE THREAD

**Issue by CodeRedDev** [Thomas-Smyth/SquadJS#338]
The introduced JS file check from #319 breaks the application. Non of the plugins will be inserted into the server plugins list and will not be mounted at all.

**Comment by werewolfboy13** [comment]
@CodeRedDev I will need server/bot logs, the QA pass that was ran passed inspection.

**Comment by rwsender** [comment]
I went commit by commit updating my SquadJS to the latest and can confirm this change caused the FTP file trail of logs not to work crashing squadJS

```FTPError: 550 \squad\SquadGame\Saved\Logs\SquadGame.log: No such file or directory
    at FTPContext._onControlSocketData (D:\projects\ripsquadjs\node_modules\basic-ftp\dist\FtpContext.js:282:39)
    at Socket.<anonymous> (D:\projects\ripsquadjs\node_modules\basic-ftp\dist\FtpContext.js:123:44)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:293:11)
    at Readable.push (node:internal/streams/readable:234:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
Emitted 'error' event on FTPTail instance at:
    at FTPTail.fetchLoop (file:///D:/projects/ripsquadjs/node_modules/ftp-tail/index.js:117:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 550
}
```

Removing this change fixes the issue

**Comment by CodeRedDev** [comment]
@werewolfboy13 when commenting the JS files section the application will have objects in `server.plugins` and will mount them.

From my understanding of the code non of the plugin's `plugin` properties in the `config.json` end with `.js`. Maybe there is a typo?

**Comment by werewolfboy13** [comment]
If this is still breaking let me know, but if this is an FTP issue it shouldn't be causing this issue.

**Comment by CodeRedDev** [comment]
> If this is still breaking let me know, but if this is an FTP issue it shouldn't be causing this issue.

I don't think rwsender's error has anything to do with this. It's a complete other component. Thanks for the quick fix :)

**Comment by CodeRedDev** [comment]
Nevermind just took another look at the changes.

https://github.com/Team-Silver-Sphere/SquadJS/blob/5be2d21183481e632d9ee2179a4d98f133b8523e/squad-server/factory.js#L85

This must be removed otherwise the error stated at the beginning of the issue won't be fixed.

**Comment by werewolfboy13** [comment]
IF this is occuring I want to see if the console logs I **will not** be approving a PR if you cant state/show why its not working.

**Comment by werewolfboy13** [comment]
![image](https://github.com/Team-Silver-Sphere/SquadJS/assets/43587009/a5745864-d4ad-4322-9d3f-cf0519798d37)

If its fixed as such will it work?

**Comment by CodeRedDev** [comment]
> ![image](https://private-user-images.githubusercontent.com/43587009/294722552-a5745864-d4ad-4322-9d3f-cf0519798d37.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ1ODQ1MjgsIm5iZiI6MTcwNDU4NDIyOCwicGF0aCI6Ii80MzU4NzAwOS8yOTQ3MjI1NTItYTU3NDU4NjQtZDRhZC00MzIyLTlkM2YtY2YwNTE5Nzk4ZDM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA2VDIzMzcwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJlYTg5MWRhZWRjOTBkNWMwN2U4MjU5NjUyOGVmZjFjN2ZlNTVhNjUxMGE1NjViYmM3Nzc4NzA4OTE3NjUyOWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ad8ViU2CnjlxO1IDvxOtDxL8460sGbQB89i0QR2vgIo)
> 
> If its fixed as such will it work?

No, the check shouldn't be in this place as I've mentioned in https://github.com/Team-Silver-Sphere/SquadJS/pull/341#issuecomment-1879875772

**Comment by watchful-eyes** [comment]
> > ![image](https://private-user-images.githubusercontent.com/43587009/294722552-a5745864-d4ad-4322-9d3f-cf0519798d37.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ1ODQ1MjgsIm5iZiI6MTcwNDU4NDIyOCwicGF0aCI6Ii80MzU4NzAwOS8yOTQ3MjI1NTItYTU3NDU4NjQtZDRhZC00MzIyLTlkM2YtY2YwNTE5Nzk4ZDM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA2VDIzMzcwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJlYTg5MWRhZWRjOTBkNWMwN2U4MjU5NjUyOGVmZjFjN2ZlNTVhNjUxMGE1NjViYmM3Nzc4NzA4OTE3NjUyOWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ad8ViU2CnjlxO1IDvxOtDxL8460sGbQB89i0QR2vgIo)
> > If its fixed as such will it work?
> 
> No, the check shouldn't be in this place as I've mentioned in [#341 (comment)](https://github.com/Team-Silver-Sphere/SquadJS/pull/341#issuecomment-1879875772)

I agree, the PR about checking the file's type is in wrong place. `pluginConfig.plugin` is the `plugin` property of the plugin's config which its name. Also what's been done already done in [squad-server/plugins/index.js](https://github.com/Team-Silver-Sphere/SquadJS/blob/master/squad-server/plugins/index.js#L23-L26)
