### ISSUE TITLE
Player list updates before rcon connection established

### ISSUE THREAD

**Issue by romanvoloboev** [Thomas-Smyth/SquadJS#358]
### Squad Information
 * SquadJS Version: 4.0.1

### System Information
 * Operating System: ubuntu
 * NodeJS Version: node:18.20.0-alpine3.19

<img width="886" alt="image" src="https://github.com/Team-Silver-Sphere/SquadJS/assets/13852208/4c1d885e-ac26-4642-af0f-488b21dd95a4">

**Comment by Trytoz** [comment]
Quite strange, I've had this problem too.
I have two different servers and they have the exact same environment
I don't have this problem on server A, but I'm having it on B.
