### ISSUE TITLE
AxiosError: getaddrinfo EAI_AGAIN raw.githubusercontent.com

### ISSUE THREAD

**Issue by romanvoloboev** [Thomas-Smyth/SquadJS#374]
getting this error after server reboot and autostart sqjs after 5 minutes:
and there is no any retreis, it's just stuck!

> | AxiosError: getaddrinfo EAI_AGAIN raw.githubusercontent.com
js-1  |     at AxiosError.from (file:///home/squad/js/node_modules/axios/lib/core/AxiosError.js:89:14)
js-1  |     at RedirectableRequest.handleRequestError (file:///home/squad/js/node_modules/axios/lib/adapters/http.js:610:25)
js-1  |     at RedirectableRequest.emit (node:events:519:28)
js-1  |     at eventHandlers.<computed> (/home/squad/js/node_modules/follow-redirects/index.js:38:24)
js-1  |     at ClientRequest.emit (node:events:519:28)
js-1  |     at TLSSocket.socketErrorListener (node:_http_client:500:9)
js-1  |     at TLSSocket.emit (node:events:519:28)
js-1  |     at emitErrorNT (node:internal/streams/destroy:169:8)
js-1  |     at emitErrorCloseNT (node:internal/streams/destroy:128:3)
js-1  |     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
js-1  |     at Axios.request (file:///home/squad/js/node_modules/axios/lib/core/Axios.js:45:41)
js-1  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
js-1  |     at async default (file:///home/squad/js/squad-server/utils/print-logo.js:23:20)
js-1  |     at async main (file:///home/squad/js/index.js:5:3) {
js-1  |   hostname: 'raw.githubusercontent.com',
js-1  |   syscall: 'getaddrinfo',
js-1  |   code: 'EAI_AGAIN',
js-1  |   errno: -3001,
js-1  |   config: {
js-1  |     transitional: {
js-1  |       silentJSONParsing: true,
js-1  |       forcedJSONParsing: true,
js-1  |       clarifyTimeoutError: false
js-1  |     },
js-1  |     adapter: [ 'xhr', 'http', 'fetch' ],
js-1  |     transformRequest: [ [Function: transformRequest] ],
js-1  |     transformResponse: [ [Function: transformResponse] ],
js-1  |     timeout: 0,
js-1  |     xsrfCookieName: 'XSRF-TOKEN',
js-1  |     xsrfHeaderName: 'X-XSRF-TOKEN',
js-1  |     maxContentLength: -1,
js-1  |     maxBodyLength: -1,
js-1  |     env: { FormData: [Function], Blob: [class Blob] },
js-1  |     validateStatus: [Function: validateStatus],
js-1  |     headers: Object [AxiosHeaders] {
js-1  |       Accept: 'application/json, text/plain, */*',
js-1  |       'Content-Type': undefined,
js-1  |       'User-Agent': 'axios/1.7.2',
js-1  |       'Accept-Encoding': 'gzip, compress, deflate, br'
js-1  |     },
js-1  |     method: 'get',
js-1  |     url: 'https://raw.githubusercontent.com/Team-Silver-Sphere/SquadJS/master/package.json',
js-1  |     data: undefined
js-1  |   },
js-1  |   request: <ref *1> Writable {
js-1  |     _events: {
js-1  |       close: undefined,
js-1  |       error: [Function: handleRequestError],
js-1  |       prefinish: undefined,
js-1  |       finish: undefined,
js-1  |       drain: undefined,
js-1  |       response: [Function: handleResponse],
js-1  |       socket: [Function: handleRequestSocket]
js-1  |     },
js-1  |     _writableState: WritableState {
js-1  |       highWaterMark: 16384,
js-1  |       length: 0,
js-1  |       corked: 0,
js-1  |       onwrite: [Function: bound onwrite],
js-1  |       writelen: 0,
js-1  |       bufferedIndex: 0,
js-1  |       pendingcb: 0,
js-1  |       [Symbol(kState)]: 17580812,
js-1  |       [Symbol(kBufferedValue)]: null
js-1  |     },
js-1  |     _maxListeners: undefined,
js-1  |     _options: {
js-1  |       maxRedirects: 21,
js-1  |       maxBodyLength: Infinity,
js-1  |       protocol: 'https:',
js-1  |       path: '/Team-Silver-Sphere/SquadJS/master/package.json',
js-1  |       method: 'GET',
js-1  |       headers: [Object: null prototype],
js-1  |       agents: [Object],
js-1  |       auth: undefined,
js-1  |       family: undefined,
js-1  |       beforeRedirect: [Function: dispatchBeforeRedirect],
js-1  |       beforeRedirects: [Object],
js-1  |       hostname: 'raw.githubusercontent.com',
js-1  |       port: '',
js-1  |       agent: undefined,
js-1  |       nativeProtocols: [Object],
js-1  |       pathname: '/Team-Silver-Sphere/SquadJS/master/package.json'
js-1  |     },
js-1  |     _ended: true,
js-1  |     _ending: true,
js-1  |     _redirectCount: 0,
js-1  |     _redirects: [],
js-1  |     _requestBodyLength: 0,
js-1  |     _requestBodyBuffers: [],
js-1  |     _eventsCount: 3,
js-1  |     _onNativeResponse: [Function (anonymous)],
js-1  |     _currentRequest: ClientRequest {
js-1  |       _events: [Object: null prototype],
js-1  |       _eventsCount: 7,
js-1  |       _maxListeners: undefined,
js-1  |       outputData: [],
js-1  |       outputSize: 0,
js-1  |       writable: true,
js-1  |       destroyed: false,
js-1  |       _last: true,
js-1  |       chunkedEncoding: false,
js-1  |       shouldKeepAlive: true,
js-1  |       maxRequestsOnConnectionReached: false,
js-1  |       _defaultKeepAlive: true,
js-1  |       useChunkedEncodingByDefault: false,
js-1  |       sendDate: false,
js-1  |       _removedConnection: false,
js-1  |       _removedContLen: false,
js-1  |       _removedTE: false,
js-1  |       strictContentLength: false,
js-1  |       _contentLength: 0,
js-1  |       _hasBody: true,
js-1  |       _trailer: '',
js-1  |       finished: true,
js-1  |       _headerSent: true,
js-1  |       _closed: false,
js-1  |       socket: [TLSSocket],
js-1  |       _header: 'GET /Team-Silver-Sphere/SquadJS/master/package.json HTTP/1.1\r\n' +
js-1  |         'Accept: application/json, text/plain, */*\r\n' +
js-1  |         'User-Agent: axios/1.7.2\r\n' +
js-1  |         'Accept-Encoding: gzip, compress, deflate, br\r\n' +
js-1  |         'Host: raw.githubusercontent.com\r\n' +
js-1  |         'Connection: keep-alive\r\n' +
js-1  |         '\r\n',
js-1  |       _keepAliveTimeout: 0,
js-1  |       _onPendingData: [Function: nop],
js-1  |       agent: [Agent],
js-1  |       socketPath: undefined,
js-1  |       method: 'GET',
js-1  |       maxHeaderSize: undefined,
js-1  |       insecureHTTPParser: undefined,
js-1  |       joinDuplicateHeaders: undefined,
js-1  |       path: '/Team-Silver-Sphere/SquadJS/master/package.json',
js-1  |       _ended: false,
js-1  |       res: null,
js-1  |       aborted: false,
js-1  |       timeoutCb: [Function: emitRequestTimeout],
js-1  |       upgradeOrConnect: false,
js-1  |       parser: null,
js-1  |       maxHeadersCount: null,
js-1  |       reusedSocket: false,
js-1  |       host: 'raw.githubusercontent.com',
js-1  |       protocol: 'https:',
js-1  |       _redirectable: [Circular *1],
js-1  |       [Symbol(shapeMode)]: false,
js-1  |       [Symbol(kCapture)]: false,
js-1  |       [Symbol(kBytesWritten)]: 0,
js-1  |       [Symbol(kNeedDrain)]: false,
js-1  |       [Symbol(corked)]: 0,
js-1  |       [Symbol(kOutHeaders)]: [Object: null prototype],
js-1  |       [Symbol(errored)]: null,
js-1  |       [Symbol(kHighWaterMark)]: 16384,
js-1  |       [Symbol(kRejectNonStandardBodyWrites)]: false,
js-1  |       [Symbol(kUniqueHeaders)]: null
js-1  |     },
js-1  |     _currentUrl: 'https://raw.githubusercontent.com/Team-Silver-Sphere/SquadJS/master/package.json',
js-1  |     [Symbol(shapeMode)]: true,
js-1  |     [Symbol(kCapture)]: false
js-1  |   },
js-1  |   cause: Error: getaddrinfo EAI_AGAIN raw.githubusercontent.com
js-1  |       at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26) {
js-1  |     errno: -3001,
js-1  |     code: 'EAI_AGAIN',
js-1  |     syscall: 'getaddrinfo',
js-1  |     hostname: 'raw.githubusercontent.com'
js-1  |   }
js-1  | }

**Comment by Thomas-Smyth** [comment]
Please follow the issue templates - they are there for a reason.

I have researched this issue and it appears to be a transient issue related to your infrastructure - it does not appear to be an issue with SquadJS.
